#ifndef PCH_H
#define PCH_H
#include <iostream>
#include "stratCRUD.h"
#include "CLadresse.h"
#include "CLcatalog.h"
#include "CLclient.h"
#include "CLcommande.h"
#include "CLpaiement.h"
#include "CLpersonnel.h"
#include "CLquantite.h"
#include "stratClient.h"
#include "stratCommande.h"
#include "stratPersonnel.h"
#include "stratStock.h"
#include "MyForm.h"
#include <iostream>
#endif //PCH_H
